// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqerfrbtnpqotszbxjbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZXJmcmJ0bnBxb3RzemJ4amJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjAxMzAsImV4cCI6MjA2MjM5NjEzMH0.I32_pTBEmS1sYuJ22NwY2M2z0kpsAd5CzLA9SdT2RDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
